### ISSUE TITLE
git prompt issues in fish 3.0

### ISSUE THREAD

**Issue by azdanov** [oh-my-fish/theme-bobthefish#181]
After updating to latest `fish 3.0` the git prompt started to misbehave.

1. Full path is shown for the second time.
<img width="1122" alt="screenshot 2018-12-28 at 21 08 19" src="https://user-images.githubusercontent.com/6123841/50525564-ddb5a100-0ae4-11e9-8fdc-9c30222b42e4.png">

2. Once line length is exceeded the cursor becomes `>`.
<img width="1122" alt="screenshot 2018-12-28 at 21 08 32" src="https://user-images.githubusercontent.com/6123841/50525565-df7f6480-0ae4-11e9-9c62-096c8a8c2e1a.png">

Is it my setup being faulty or `3.0` broke something?

**Comment by bobthecow** [comment]
It wouldn’t surprise me if it is 3.0. I’ll take a look next week when I’m back to my computer :)

**Comment by bobthecow** [comment]
The `>` is [just how fish works](https://fish-shell/fish-shell/issues/904) when your prompt is too long.

Including your home directory is weird, but, based on the two strings, my guess is it's because of `Projects` vs `projects`. Why are they different cases?

**Comment by azdanov** [comment]
> The > is just how fish works when your prompt is too long.

Didn't know this.

> Including your home directory is weird, but, based on the two strings, my guess is it's because of Projects vs projects. Why are they different cases?

Original is `Projects`, no idea why it's lowercased and repeated.

**Comment by azdanov** [comment]
I've fiddled around a little bit and after renaming `Projects` to `projects` everything started to work as before the update.

Closing since the issue is resolved.

**Comment by bobthecow** [comment]
it’s still weird that the case is different. i don’t love that the answer is “change your filesystem” :-/

**Comment by z3ntu** [comment]
I also see the "full path shown as path in git repository" issue on Linux with an ext4 filesystem

**Comment by bobthecow** [comment]
what do `git rev-parse --show-toplevel` and `pwd` show in a directory with this issue?

**Comment by z3ntu** [comment]
Found a way to easily reproduce the issue:
```
cd /tmp
mkdir dir1
ln -s dir1 dir2
cd dir2
git init
```

```
$ git rev-parse --show-toplevel
/tmp/dir1
$ pwd
/tmp/dir2
```

**Comment by azdanov** [comment]
@bobthecow Nice, it does seem to work as before. Thanks!

**Comment by bobthecow** [comment]
@z3ntu thanks, I'll take a look.

**Comment by rousseldenis** [comment]
It seems I have quite the same issue but fish 2.7.1

![image](https://user-images.githubusercontent.com/19529533/51245920-5348ba80-1989-11e9-9187-7e515800e3d3.png)

**Comment by bobthecow** [comment]
@rousseldenis I'm not sure I understand what issue you're having, other than the vertical lines.

**Comment by ben-watt-es** [comment]
I am having issues where often the prompt will not show at all until I cd back into the same directory.

By this I mean that sometimes I enter a git directory and the git prompt shows as expected. It often does not stay if I cd into a subdirectory (it disappears completely). cd'ing to the root will fix this most of the time, but not always; sometimes I just cannot get the git prompt to show in the root dir at all.

Initially I thought the flag for enabling / disabling worktree support affected this, but after some testing it makes no difference.

It was all working as expected for me until I did a clean reinstall - previously I was using a fish 2.x version and a much older revison of bobthefish.

**Comment by bobthecow** [comment]
@ben-watt-es yeah, fish 3 changed the way pwd works, so it gets a little weird with case insensitive filesystems. Are you running the latest bobthefish? It should be worked around in 4ccdd7bdcfd615e991321dbc811be69d3b94f2d7

**Comment by azdanov** [comment]
@bobthecow I've had the same issues where `cd`ing into `/Users/azdanov/projects/node` instead of `/Users/azdanov/Projects/node` caused some issues, with Git indicator in particular. Took me a while to figure out it was case sensitivity all along.

And thanks for your hard work!

**Comment by bobthecow** [comment]
All permutations of this should now be resolved. Feel free to re-open if you run into it again :)

**Comment by z3ntu** [comment]
That fixes my use case at least :)

What seems to be a bit not-exactly-intuitive behavior is that the prompt shows the "real" (=resolved) parent directory of your current one, so for example doing `cd ..` is not very intuitive as you're not getting into the directory you're expecting to go ;) Just a minor complaint though

**Comment by bobthecow** [comment]
Yeah, I don’t love it, but I didn’t love the alternatives either.

When we interact with external services like `git`, or `hg`, or whatever, which bobthefish does a lot of, we need to talk about paths in terms of things they understand. And if we _only_ use resolved paths when talking to external services, it gets weird mapping them back to the fishy paths we use internally. So I went with always referring to things by canonical paths, because it was less awful.

The other option, which I poked at but didn’t get very far, would be to _always_ refer to things by their internal paths, and do try to map external services’ idea of paths back into what fish things the pwd is. If you wanna take a shot at it, I’d be happy to entertain a pull request :)

**Comment by Climax777** [comment]
Mine still doesn't work with bobthefish

```
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.20.1
Git core.autocrlf:    no
```

![image](https://user-images.githubusercontent.com/768925/60798427-705c8a00-a171-11e9-8120-f9c654a75509.png)

**Comment by Climax777** [comment]
It seems to be related to the `c++` part of the path. Moving my project to `cpp` for example works, but adding a `+` to any folder in the path breaks it for me.

**Comment by Climax777** [comment]
Could this be related to git or is the output of this correct?
```
$ git rev-parse --show-toplevel
/home/pieter/Documents/Programming/c++/secuvue-agent
$ pwd
/home/pieter/Documents/Programming/c++/secuvue-agent/build
```
